#!/usr/bin/env ruby

images = Dir["images/speakers/*-original.jpg"]

options = [
  "-resize 640x360",
  "-extent 640x360",
  "-gravity Center",
  "-quality 90"
].join(" ")

images.each do |img|
  base = img[/^.+(?=-original)/]
  ext = File.extname(img)
  out = base + ext
  `convert #{img} #{options} #{out}`
end
